### PR TITLE
Fix deprecations in PHP 8

### LINKED ISSUE #13: Deprecated warnings with PHP 8
Hi,

With PHP 8 the method [ReflectionParameter::getClass()](https://www.php.net/manual/de/reflectionparameter.getclass.php) is deprecated and can be replaced by [ReflectionParameter::getType()](https://www.php.net/manual/de/reflectionparameter.gettype.php).

I am getting a lot of deprecations [caused by this code](https://github.com/handcraftedinthealps/RestRoutingBundle/blob/master/Routing/Loader/Reader/RestActionReader.php#L430):
Bildschirmfoto 2021-06-04 um 12 04 01
 
@alexander-schranz As this bundle requires PHP 7.2 and `ReflectionParameter::getType()` is available since 7.1, we should be able to safely change the code, correct?

### PR DESCRIPTION
**Pull request by kevinpapst**
Fixes #13

### CODE REVIEW

**Review by alexander-schranz — APPROVED** [review]
Looks good from my side. Do you have any open issues?

**Comment by kevinpapst** [comment]
Do you have an idea how that can be tested properly, besides manual checks? 
I couldn't entirely grasp where this code is used and what it is for.

I just see the triggered deprecations, so the code path is used.

**Comment by alexander-schranz** [comment]
Most things are tested here over the `UsersController` test I think: https://github.com/handcraftedinthealps/RestRoutingBundle/blob/d0e43e7f12bb6a24f1feaef29a42e1684023fa64/Tests/Routing/Loader/RestRouteLoaderTest.php#L29-L46 which just test it against some `yaml` configuration.

**Comment by kevinpapst** [comment]
I will do some more testing and come back to you later

**Comment by alexander-schranz** [comment]
@kevinpapst just ping me if you think its ready :)

**Comment by kevinpapst** [comment]
Results from my API integration test suite:

PHP 7.4 with this branch worked without problems.

PHP 8 with master:
```
OK (240 tests, 2740 assertions)
Unsilenced deprecation notices (386)
Remaining indirect deprecation notices (10)
```

PHP 8.0 with this branch
```
OK (240 tests, 2747 assertions)
Unsilenced deprecation notices (18)
Remaining indirect deprecation notices (10)
```

The left over deprecations are coming from other bundles ... one fix after another 😁 

Everything seems to work as before. 
Please note that I have not tried to use explicit PHP 8 features (namely the union types).
All I wanted to fix in this step was the deprecation.

@alexander-schranz from my side: good to go

**Comment by alexander-schranz** [comment]
@kevinpapst Thank you!

**Pull request merged**
